version: '3.7'
#-----------------
# Docker-compose to bring up invasive_checker API
#-----------------

services:
  aphia_checker_test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - ./tests/:/tmp/tests/
    command: python /code/app/main.py -l INFO -i /tmp/tests/test_data/worms2.csv -o /tmp/tests/output/
    logging:
      driver: json-file
      options:
        max-size: 10m 
 