version: '3.7'
#-----------------
# Docker-compose to bring up invasive_checker API
#-----------------

services:
  aphia_checker_test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - ./tests/:/mnt/tests
    command: python /code/app/main.py -l DEBUG -i /mnt/tests/test_012023/final_table.tsv -m /mnt/tests/test_012023/ARMS4Tesseract_PEMA_data.csv -o /mnt/tests/test_012023/output/
    logging:
      driver: json-file
      options:
        max-size: 10m 
