version: '3.7'
#-----------------
# Docker-compose to bring up invasive_checker API
#-----------------

services:
  aphia_checker_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${API_PORT}:8090
    restart: unless-stopped 
    logging:
      driver: json-file
      options:
        max-size: 10m 
 