FROM python:3.9-slim-buster

WORKDIR /wrims
COPY app/ app/
COPY invasive_checker/ invasive_checker/
COPY requirements.txt . 
COPY README.md .
COPY setup.py .
RUN pip3 install -r requirements.txt
RUN pip3 install .
ENTRYPOINT [ "python" ,"app/main.py" ]