version: '3.7'
#-----------------
# Docker-compose to bring up invasive_checker API
#-----------------

services:
  aphia_checker_test:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  
    volumes:
      - ./tests/:/tmp/tests/
    command: python /code/app/main.py -l DEBUG -i /tmp/tests/test_Dec_2022/final_table.tsv -m /tmp/tests/test_Dec_2022/ARMS4Tesseract_PEMA_data.csv -o /tmp/tests/test_Dec_2022/output/
    logging:
      driver: json-file
      options:
        max-size: 10m 
 